name: Multi-Env CI/CD

on:
  push:
    branches:
      - dev
      - uat
      - main

jobs:
  dev_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - run: echo "Deploying to DEV..."

  uat_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/uat'
    environment: uat
    steps:
      - uses: actions/checkout@v3
      - run: echo "Deploying to UAT..."
      
  prod_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: prod
    steps:
      - uses: actions/checkout@v3
      - run: echo "Deploying to PROD..."
